import {
  Box,
  ChakraProvider,
  Drawer,
  DrawerContent,
  useDisclosure,
} from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderBar from "./components/HeaderBar";
import FooterBar from "./components/FooterBar";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <React.Fragment>
            <HeaderBar />
          </React.Fragment>
          {children}
          <React.Fragment>
            <FooterBar />
          </React.Fragment>
        </ChakraProvider>
      </body>
    </html>
  );
}
